### ISSUE TITLE
How to decrypt messiah opcode!

### ISSUE THREAD

**Issue by x4317350** [xforce/netease-messiah-tools#6]
Hello, first of all thank you for your work!

I tried to decrypt PYC on other Netease Games based on Messiah Engine, but encountered many difficulties!
Can you tell me how the opcode in the 'get_messiah_opcodes' function in the' [pyc_retarget.py'](https://github.com/xforce/netease-messiah-tools/blob/main/pyc/scripts/pyc_retarget.py)  file was found and analyzed!

For example,
`def_op('LOAD_FAST_LOAD_ATTR_LOAD_FAST_CALL_FUNCTION', 193)

messiah_opcodes.LOAD_FAST_LOAD_ATTR_LOAD_FAST_CALL_FUNCTION: [
                opc.LOAD_FAST,
                opc.LOAD_ATTR,
                opc.LOAD_FAST,
                opc.CALL_FUNCTION,
            ]`

how to find the 193 opcode and analyze the corresponding operation of the 193 opcode

Thanks very much!

**Comment by xforce** [comment]
I mentioned this elsewhere, for the time-being, the target game is Diablo Immortal until such time comes where I have all the building blocks in-place to expand support to other games.
As for the opcodes, it's likely that they have change/are different across the range of Messiah Based games.
Generally the process is as follows.
1. Grab the game binary from somewhere.
2. Open it in some kind of static analyzer (I personally use IDA Pro, but there are others).
3. Find `PyEval_EvalFrameEx`, usually accomplished by looking for strings that are referenced in that function.
4. Start reverse engineering the jump table there and map each opcode

If you tell me what game this is for and what difficulties you experienced exactly I might be able to offer better guidance

**Comment by x4317350** [comment]
> 

i’m grateful for you help!
The game is based on the NEOX engine.[https://www.harrypottermagicawakened.com/cn/](url)。
It contains some custom Opcode, and i think, maybe it is possible to analyze Custom Opcode in the same way. 
Or, maybe you have othrer better suggestion.
